### ISSUE TITLE
Replace fixer.io with exchangerates.io

### ISSUE THREAD

**Issue by cromica** [KirillOsenkov/QuickInfo#41]
While fixer.io provides a free tier it does require and API key. This can be a bit of an issue if the library is used from a desktop application as it will require building a mechanism to provide the access key (and the potential not technical user to create such a key). Using https://exchangeratesapi.io/ is free and doesn't require any key. More than that it's API is fully compatible with fixer.io.

I see 3 potential options:

1. Replace fixer.io with exchangerates.io in the current implementation.
2. Build a mechanism that allows specifying the api in the quickinfo library. 
3. I can just build my own currency processor. However I thought it could be potentially beneficial for library consumers.

I would be happy to provide a PR with the changes for the first 2 options if you consider them.

**Comment by KirillOsenkov** [comment]
Can you send a PR for option 1? I don’t have any reasons to stay with fixer.

**Comment by KirillOsenkov** [comment]
This is now fixed, thanks.
