### ISSUE TITLE
Simple currency converter?

### ISSUE THREAD

**Issue by VladimirRybalko** [KirillOsenkov/QuickInfo#8]
What do you think about a simple currency converter?

**Comment by KirillOsenkov** [comment]
Not a bad idea, just not sure where to get fast, free and accurate rates service. I didn't investigate because Google does a decent job here.

**Comment by VladimirRybalko** [comment]
Generally, I suggest to use http://fixer.io/
It's free and pretty simple. However I'm not sure about accuracy. Need to check it.

**Comment by KirillOsenkov** [comment]
Seems easy enough. Fetch these lazily once per day and use for "400 EUR in USD" kind of queries. Might even use the Unit Conversion infrastructure for this: https://github.com/KirillOsenkov/QuickInfo/blob/master/src/QuickInfo/Processors/Converters/Units/Units.cs

**Comment by VladimirRybalko** [comment]
Related PR #10

**Comment by KirillOsenkov** [comment]
Deployed! Thanks for the contribution. Like your balance of pragmatism and simplicity (solution is not very generic as you say, but good enough for now).

**Comment by KirillOsenkov** [comment]
Actually I've just realized that this can easily scale to arbitrarily many currencies. You just need to provide conversions to EUR and back. The unit conversion engine will automatically deduce transitive conversions.

**Comment by KirillOsenkov** [comment]
Here, fixed and it still works the same:
https://github.com/KirillOsenkov/QuickInfo/commit/0eb34cd3a2f2020c5bb7f287eaf36765a7a9ffab

**Comment by VladimirRybalko** [comment]
It's cool!
I couldn't even imagine that Quick info supports transitive conversions without any code changes.
