### ISSUE TITLE
Error in currency conversion

### ISSUE THREAD

**Issue by oscaretu** [KirillOsenkov/QuickInfo#91]
Hello.

I've gone to URL https://quickinfo.io/?150%20EUR%20in%20USD and the result is wrong (the right one can't be 0).

![imagen](https://user-images.githubusercontent.com/2979926/205504989-948807d1-7be2-4e02-af2e-a2d3c574abbb.png)

**Comment by KirillOsenkov** [comment]
Thanks for letting me know. This should be fixed now.
