### ISSUE TITLE
Country codes

### ISSUE THREAD

**Issue by KirillOsenkov** [KirillOsenkov/QuickInfo#98]
https://github.com/datasets/country-codes

**Comment by ramtejsudani** [comment]
<img width="366" alt="image" src="https://github.com/KirillOsenkov/QuickInfo/assets/9163421/6bc9d1d7-5835-4b11-812e-0abe82b45187">
[country-codes_final.csv](https://github.com/KirillOsenkov/QuickInfo/files/12420674/country-codes_final.csv)

Hi @KirillOsenkov , Does this looks good for the country info?  I have attached the filtered columns for country data as well for your reference. Please let me know if any changes. If it's good, I will raise the PR for the code change- https://github.com/ramtejsudani/QuickInfo/blob/AddCountryCodes/src/QuickInfo/Processors/CountryCodes.cs

**Comment by KirillOsenkov** [comment]
Yes, this looks good, you can open a PR.

**Comment by KirillOsenkov** [comment]
Hmm, I thought it had telephone dialing code for countries, e.g. it should show +91 for India or +49 for Germany

**Comment by ramtejsudani** [comment]
My Apologies, I missed out on adding the dialing code line in the code.

**Comment by ramtejsudani** [comment]
> Hmm, I thought it had telephone dialing code for countries, e.g. it should show +91 for India or +49 for Germany

My Apologies, I missed out on adding the dialing code line. Updated it.
